### ISSUE TITLE
(error: Invalid string length)

### ISSUE THREAD

**Issue by jrwhitehead** [theopolisme/location-history-visualizer#12]
I followed the instructions by downloading my google takeout location data in JSON format. I uploaded it but the following occurred:

NOTE: It worked in google takeout kml format. JSON file size was 216MB.

Something went wrong generating your map. Ensure you're uploading a Google Takeout JSON file that contains location data and try again, or create an issue on GitHub if the problem persists. (error: Invalid string length)

This will take a while... sit back, get a cup of tea or something.

Why does it take so long? Depending on how long Google's been tracking your location, you may have hundreds of thousands of [latitude, longitude] pairs, every one of which must be loaded, analyzed, and plotted. That's a lot of dots.

**Comment by pierlauro** [comment]
The error could be caused by the *JSON.parse* call in *getLocationDataFromJson* because the file is too big.

Try to use [this version](https://github.com/pierlauro/location-history-visualizer/tree/json_parser) I just committed of my fork of the project on the branch json_parse.

(You can download and the unzip the entire branch [from here](https://github.com/pierlauro/location-history-visualizer/archive/json_parser.zip)).

Let me know if it solve the issue this way.

**Comment by caffinatedmonkey** [comment]
[It's because of this commit](https://github.com/theopolisme/location-history-visualizer/commit/a7763844fa7fce264958f6807250a6405dad63b4). Remove it and everything should be fine.
